version: '3'

# TODO(dio): use `expose` instead of `ports` for following services.
services:
  plain.front:
    build: envoy/front/plain
    ports:
      - 8000:8000
    depends_on:
      - api
    networks:
      - internal
      - external

  secure.front:
    build: envoy/front/secure
    image: sample_secure_front:latest
    ports:
      - 8001:8001
    depends_on:
      - api
      - cert
    networks:
      - internal
      - external

  greeter:
    build: services/hello
    ports:
      - 5001:5001
    depends_on:
      - api
    networks:
      - internal

  internal:
    build: envoy/internal
    ports:
      - 10000:10000
    networks:
      - internal

  address.internal:
    build: services/address
    ports:
      - 3001:3001
    depends_on:
      - api
    networks:
      - internal

  bio.internal:
    build: services/bio
    ports:
      - 3002:3002
    depends_on:
      - api
    networks:
      - internal

  client:
    build: client
    depends_on:
      - api
      - cert
    networks:
      - internal
      - external

  api:
    build: api
    image: sample_api:latest

  cert:
    build: cert
    image: sample_cert:latest

networks:
  external:
  internal: