admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: internal_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/people.Address" }
                route: { cluster: service_address }
              - match: { prefix: "/people.Bio" }
                route: { cluster: service_bio }
          http_filters:
          - name: envoy.router

  clusters:
  - name: service_address
    connect_timeout: 25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: address.internal, port_value: 3001 }}]
    health_checks:
      - timeout: 25s
        interval: 1s
        unhealthy_threshold: 1
        healthy_threshold: 1
        grpc_health_check: { }
  - name: service_bio
    connect_timeout: 25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: bio.internal, port_value: 3002 }}]
    health_checks:
      - timeout: 25s
        interval: 1s
        unhealthy_threshold: 1
        healthy_threshold: 1
        grpc_health_check: { }